Repository apiflask/apiflask, pull requests merged in 2022-02, with the labels that each got.

#203 Replace deprecated pypy3 with pypy-3.8
  .github/workflows/tests.yml
  tox.ini
Labels: CI

#201 missing a " ' "
  docs/usage.md
Labels: docs

#204 Update requirements
  requirements/dev.txt
  requirements/docs.txt
  requirements/examples.txt
  requirements/tests.txt
  requirements/typing.txt
Labels: dependencies
